### PR TITLE
Add new zes package

### PR DESCRIPTION
**Pull request by cachesdev**
zes package contains spanish translations for validation errors and should be compatible with the i18n package.

### CODE REVIEW

**Comment by cachesdev** [comment]
some observations: 
- I thought of creating a concise version with concise errors. it will just be a another map with different errors, whoever that can add a maintenance burden.

- I am also not too sure about the article use (La, El, etc)

- For arrays, I thought of using either `Lista` or `Coleccion`, the latter felt better but we can change things of course.

- I am not too sure about the struct translation. it doesn't tell the end user much information about what is actually being validated, but I also can't think of a better message. I would appreciate some feedback here

**Comment by Oudwins** [comment]
Thanks a lot for this.

Some thoughts:

1. This should be `una` for sure. I also feel like we should be able to find better wording for this.
```go
		zconst.ErrCodeOneOf:           "La cadena debe ser uno de los siguientes: {{one_of_options}}",
```

2.  What do you think about dropping the article at the start for all? (i.e making it "cadena debe contener al menos {{min}}..." instead of "La cadena"

3. Personalmente prefiero lista a colección, creo que colección es demasiado generico

4. The struct is complicated. I feel like if you are showing validation messages related to a struct to a user you probably need a custom validation message so we should just write the message for the dev. What do you think?

**Comment by cachesdev** [comment]
I made the changes.

i've noticed a possible error here;
```go
		zconst.ErrCodeMin:             "Cadena debe contener al menos {{min}} caracter(es)",
		zconst.ErrCodeMax:             "Cadena debe contener como máximo {{min}} caracter(es)",
```

it's also in `Errors.go`

**Comment by Oudwins** [comment]
You are right. That is a typo on my end. I just fixed it and also moved the English map to follow the new convention (i.e be inside the i18n package). 

Would you mind changing the min to max here. After that I am happy to merge this!

**Comment by cachesdev** [comment]
that should be it, fixed the typo and changed the package name

**Pull request merged**
